### ISSUE TITLE
Snippet: search form

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#63]
### zeplin links
list with results: [L](https://zpl.io/adM1x65) / [M](https://zpl.io/V0E1J3E) / [S](https://zpl.io/29DQDky)
### notes
- [x] issues with histogram will be tracked on ~#66~ #34
- [x] issues with sort controls will be tracked on #64 
- [x] issues with pagination will be tracked on #46 
- is the form responsive?
- does the form submit when you expect it to?

**Comment by thatbudakguy** [comment]
## testing notes
- author and title search are disabled as they aren't mvp and aren't implemented yet.
- still need to insert a "to" in between the pub date inputs...working on this with help from @rlskoeser 
- booleans ("show only", "exclude") are disabled as they aren't implemented yet.
- keeping the little "submit" button for now until we add javascript submission logic in #65 
- histogram will be implemented in #66 
- changing sort should submit the form.

**Comment by jabauer** [comment]
- Author and Title Search now work
- to has been inserted
- hitting enter makes the form update so submit could be removed
- histogram is in place
- responsive on the following systems 
--MacPro 15" Retina mid 2014 running OSX10.13.4 with following browsers
--Chrome v66.0.3359.139
--Safari v11.1
--Firefox v57.0.4
-iPad Pro running iOS 11.3.1
--Safari
-iPhone 6 running iOS 11.3.1
--Safari
-iPad Air 2 running iOS 11.2.5
--Safari

**Comment by xinyil** [comment]
- submit the year range filter on click out. it's not likely that people will press the "enter" key here, especially when there're the arrow adjust buttons.

**Comment by xinyil** [comment]
all collections in the about page should have a button in the filter form. otherwise, when I click into the browse page from the grammar title on about page, I got no result, and there's no way to unselect "grammar" because it's not here in the form.

**Comment by thatbudakguy** [comment]
[adding @jabauer comment from #34 ]

Timeline displays properly most sizes of screens. Responsive, although it takes up space on small mobile devices (see Zeplin mockup for small screen, meant to be keyword search only).
On iPad Air 2 (and mid-point resizing window on larger screen) you get this 
![image](https://user-images.githubusercontent.com/243947/40256114-6e6ff468-5ab7-11e8-8685-9b4fe46a9533.png)

Displays probably on following systems:
* MacPro 15" Retina mid 2014 running OSX10.13.4 with following browsers
	* Chrome v66.0.3359.139
	* Safari v11.1
	* Firefox v57.0.4
* iPad Pro running iOS 11.3.1
	* Safari
* iPhone 6 running iOS 11.3.1
	* Safari

**Comment by rlskoeser** [comment]
@xinyil regarding this:
> all collections in the about page should have a button in the filter form. otherwise, when I click into the browse page from the grammar title on about page, I got no result, and there's no way to unselect "grammar" because it's not here in the form.

I can't return collections from Solr that aren't there at all.  I think we need to do one of the following:
1. Don't display collections that have zero items
2. Display collections with zero items but don't link to search 

> also add "on click" status for the collection tags, same style as on hover. this is really useful for touchscreen devices so you know where you clicked.

I think this has been addressed, was tested in #77

**Comment by thatbudakguy** [comment]
@rlskoeser maybe we can just show all collections that are in the database and then use the solr data to set them to `disabled` if they don't have items?

**Comment by xinyil** [comment]
> also add "on click" status for the collection tags, same style as on hover. this is really useful for touchscreen devices so you know where you clicked.
I looked at #77, and currently collection tags have "active" state but not "on click"

can we:
- in filter section: disable the collections that have zero items
- on about the collection page: Display collections with zero items but don't link to search

**Comment by rlskoeser** [comment]
@xinyil please review updates:
*  Search form should now display all collections in the database, but those with no items in Solr are disabled.  
* collection page displays collections with zero items but does not link to search

**Comment by xinyil** [comment]
they interact as expected.

a few things related to style:
- on about the collection page, disabled tile shouldn't react on hover
- in the filter section and disabled tags are missing the outline.


to be fixed later:
- add "on click" status for the collection tags, same style as on hover. this is really useful for touchscreen devices so you know where you clicked.

**Comment by rlskoeser** [comment]
@xinyil fixed the disabled tile hover on collection page. Not sure why the disabled tags are missing outline, but we're using default semantic styles for now so I think this is ok to handle in the next round.

**Comment by xinyil** [comment]
these have not been fixed:
- when there're active search terms, add the delete button for the three search fields.
- on M, text and icons of the edition selection checkboxes overlap. 

will move this one to #88
- add "on click" status for the collection tags, same style as on hover. this is really useful for touchscreen devices so you know where you clicked.

**Comment by xinyil** [comment]
tracking remaining issues in #90
closing
