### ISSUE TITLE
As a content editor, I want to add new or edit existing editorial content so that I can publish and promote scholarly work related to the project.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#99]
## notes for testing
This should be testable in its most basic form, because a lot of the more involved functionality has been pushed off to other user stories.
- In the wagtail CMS, navigate to where you can see `Editorial` in the hierarchy and choose 'add child page'. It should work pretty much the same as a content page. 
- When you publishing an editorial page, it should be listed on the main 'Editorial' page on the public site, and should link to the individual page you created.
- The page url for editorial content should look like `/editorial/year/month/page-slug/`
- Reverting a published editorial essay to draft should make it not be listed on the editorial list page.

## dev notes
Should be structured like a blog. 
- [x] add author selector; support multiple authors; ordered many to many to allow editors to determine/preserve author order (author = snippet?) [now part of #150]
- [x] determine if we ned explicit pub date; if so, auto populate to today
- [x] generate url/slug based on pub date
- [x] enable tags [now #151 / #152]
- [x] custom image model with caption (= title?), alt text, optional copyright statement / license [#153]
- [x] custom document model with optional author [#154]
- [x] add image field for twitter card / unfurl / open graph preview [#155]
- [x] ~(nice to have) ppa page image chooser?~ [#156]
- [x] semantic / rdfa tags for blog? (or json-ld) [#157]
- [x] rss feed [#158]
- [x] optional formatted description for preview; strip tags -> search description if not set. preview text method to get formatted description or beginning of post if not set. [#159]

**Comment by mnaydan** [comment]
- My sense is that this should be structured like a blog--as Xinyi's tile design also suggests visually, I think. It should be flexible enough that we can have a range of content--from essays with pictures to lesson plans (downloadable attachment would be great) to resource lists (bullet point lists), with the most recent content displayed on top on the main page and each tile linking to the individual page. 
- Each content item would have one or more authors whose names should be displayed. I could see us wanting the author(s) name(s) displayed on the tiles and the individual content pages, especially if Board Members contribute content. Only certain admins would be able to publish posts--ie, me and Meredith. Does that answer your question? 
- Idk what wagtail is. I looked it up and that seems fine (and perhaps more flexible than WYSIWYG editor?) We would probably be copying and pasting content that was produced on a word doc or google doc, so whatever is most amenable to that? Lmk if that clarifies or you need more info.

**Comment by thatbudakguy** [comment]
@mnaydan sorry for not adding more detail to this! for a little more context, check out [this video](https://www.youtube.com/watch?v=oUJNweMWwVQ) (if you haven't already seen it) of what editing content in wagtail looks like. The approach is a little different from the current editor, but I think you're right that it's more flexible.

I noticed that we don't have author names on the editorial list or even the posts themselves in the design, which seems a little weird - shouldn't be hard to add.

**Comment by rlskoeser** [comment]
@mnaydan thanks for the feedback on the kind of content, super helpful. Yes, our hope is that wagtail will be more flexible and easier to use.

@mnaydan question: on posts with more than one author, do you want to be able to control the order of names? 

@thatbudakguy agreed, it seems weird to omit author from the list and post views; we probably want publication date, too?  I noticed a similar thing on the derrida outwork list view, authors are not displayed (original publication date is).

**Comment by mnaydan** [comment]
thanks @thatbudakguy that's the same video I found! It looks like it's better for copying and pasting content than the WYSIWYG editor, so that sounds good.

@rlskoeser Yes, controlling the order of names would be great if it's easy enough. 

And I agree with you and @thatbudakguy on wanting author name(s) and publication date on list and post views. Hopefully that's not too hard to add in? (I think Meredith and I missed this during design because we kept kicking editorial down the road...)

**Comment by rlskoeser** [comment]
@mnaydan when you get a chance: where should the blurb/preview text used on the card display for an editorial post come from?  Is this just the beginning of the post, truncated? Should we use the meta description that you can enter separately (this is the preview text displayed for links in Slack or on Twitter)? Do you want a dedicated field for this?

**Comment by mnaydan** [comment]
@rlskoeser do you think we should do it how it is in CDH web with the "Description" field that is autogenerated but also able to be changed manually?

**Comment by rlskoeser** [comment]
@mnaydan it works a little differently in wagtail, but I think we could do something equivalent: use the search description field if it's set, use the beginning of the post text if it isn't?

**Comment by mnaydan** [comment]
@rlskoeser yes, that sounds perfect to me. So, description wouldn't be a required field but it would take priority if it is filled out, if that makes sense. If it's not filled out, use beginning of post.

**Comment by rlskoeser** [comment]
@mnaydan one wrinkle (and something I think we've actually had some problems with in CDH web): the search description doesn't support formatting. Does that change your answer?

**Comment by mnaydan** [comment]
@rlskoeser so if I wanted to italicize a title on the manually set description, I couldn't? Boo. I suppose we should just draw it from the beginning of the post then.

**Comment by rlskoeser** [comment]
@mnaydan following up on this: what I think we should do instead is add an optional formatted description field. We can use that to generate the description text by removing tags (unless you manually enter a different description), and if you don't provide one we can just use the beginning of the page content for the preview.  

How does this sound? And what name makes sense to you for this field? The plain-text description field in Wagtail is called "search_description", but we don't have to use that. Description? Preview?

**Comment by mnaydan** [comment]
@rlskoeser I don't know what you mean by "generate the description text by removing tags", but it sounds like this is a work around that will support formatted manual description, and default to beginning of post if no manual description is set? If so, this sounds good to me. I find "search_description" confusing as a label. "Description" makes the most sense to me.

**Comment by mnaydan** [comment]
All of this functionality works! Can add a page in wagtail, and when you publish it it appears on the main editorial page. The tile links to the individual page. Page url is correct. When you unpublish the post it disappears from the public site.

The tile design is the old design and there are some design problems on the individual page but that's part of other user stories I presume.
